solid-contrib/specification-tests

protocol/converted/test_3-3.feature
protocol/converted/test_3-5.feature
protocol/converted/test_4-3.feature
protocol/converted/test_4-7.feature
protocol/converted/test_5-3.feature
protocol/converted/test_5-5.feature
protocol/converted/test_5-7.feature

This allows more successful codes for several `PATCH` and `POST` operations. This is somewhat assuming that the conclusion of https://github.com/solid/specification/issues/288 is that we do not define status codes for everything, but I think these are a few cases where it is OK to accept more successful codes.

More lenient tests for successful requests

---

protocol/authentication/header.feature
protocol/solid-protocol-spec.ttl
protocol/solid-protocol-test-manifest.ttl

The protocol does not need much with respect to compliance from RFC 7235, just make sure it gets a `401` and a header for unauthenticated agents.

A simple Authentication header test

---

protocol/solid-protocol-spec.ttl
protocol/solid-protocol-test-manifest.ttl
protocol/writing-resource/slash-semantics-exclude.feature

This is a first attempt at testing that a server cannot have both a container and a resource that differs only by trailing `/`.
I struggle to understand which response belongs to what request, so I'm confident the tests are correct yet. 
```
2021-09-08 00:19:20,676 DEBUG [com.int.karate] (pool-2-thread-1) request:
1 > PUT https://pod.inrupt.com/solid-test-suite-alice/shared-test/6ae92b44-5671-44d1-8b06-4f63aef47e07/ad2f6827-50c3-4686-a901-3568bc6121fc/foo/
1 > Authorization: DPoP ***ftNPfA
1 > User-Agent: Solid-Conformance-Test-Suite
1 > DPoP: ***BXmSWw
1 > Host: pod.inrupt.com
1 > Connection: Keep-Alive
1 > Accept-Encoding: gzip,deflate
2021-09-08 00:19:20,676 DEBUG [com.int.karate] (pool-2-thread-2) request:
1 > PUT https://pod.inrupt.com/solid-test-suite-alice/shared-test/6ae92b44-5671- …
```

Test for slash semantics exclusion

---

protocol/converted.ttl
protocol/solid-protocol-spec.ttl
protocol/solid-protocol-test-manifest.ttl

I suggest we use a prefix for the protocol document in the manifest (and similar). It'll make it feasible to type.

Use a prefix for the protocol

---

test-subjects.ttl
web-access-control/protected-operation/acl-propagation.feature

Added ESS1.2 and clarified the wac/acp support of all servers - test-subects.ttl.
In one test case, opened up response codes and remove logging which will be done better in the next test harness release.

Add new server and improve ACL test

---

protocol/solid-protocol-test-manifest.ttl
web-access-control/web-access-control-test-manifest.ttl

Currently, all Conformance Test Suite tests are marked as 'unreviewed'. To reduce the overhead required from the Solid Editors to review and approve the tests, it was proposed that 'uncontroversial' tests could be bulk approved.
To determine the tests to 'approve', the Conformance Test Harness was executed against CSS, ESS (ACP & WAC), and NSS and the results analysed:
- If a test passed all servers, or passed most servers with expected failure on some servers (e.g., WAC-allow tests failed on ESS (ACP) as WAC-allow headers are not implemented), it is assumed the test is correct, and the review status was updated to 'approved'.
- If a test failed unexpectedly against any server, the review status was left as 'unreviewed'.
Note: The analysis has been deliberately not been included in this …

Bulk move uncontroversial tests to 'approve' review status

---

CHANGELOG.md
README.md

If this PR is OK, then I propose to set the repo to v0.0.1. Then I can work on how the you can run CTH with a specific version of tests, pass that version number into reports and determine if the version is the latest.

Add notes about versioning and a changelog

---

protocol/solid-protocol-test-manifest.ttl
protocol/writing-resource/uri-assignment.feature

This is focused on the requirement URI assignment using `PUT` and `PATCH`. The `PUT` test should be OK, but for the `PATCH`, it needs to go in after the merge of https://github.com/solid/specification/pull/346 I'm also not 100% sure about the syntax, so it should be reviewed for that too. I've added an `@ignore` tag for that reason.

URI Assignment with PUT and PATCH

---

protocol/resources/describedby-unique.feature
protocol/solid-protocol-test-manifest.ttl

The intention here is to test for the presence of at most one describedby link. 
NSS will always have exactly one link, and that's required for discovering the feature, but the spec says nothing to require it. So, I made a last commit to relax that.

Test for presence of at most one describedby link

---

protocol/read-write-resource/method-not-allowed.feature
protocol/solid-protocol-test-manifest.ttl

Here's an attempt to use the new `sendAuthorized` method in the harness. I get the following error though:
```
org.graalvm.polyglot.PolyglotException: TypeError: invokeMember (sendAuthorized) on org.solid.testharness.api.SolidClient@4e52d2f2 failed due to: Unknown identifier: sendAuthorized
```
I don't know if this means that I somehow haven't gotten the harness updated here, or if there's something wrong in the setup. So, I just made this so that I can work on other things while we check that our.

Non-working test for method not allowed

---

protocol/read-write-resource/read-method-allow.feature
protocol/solid-protocol-test-manifest.ttl
protocol/writing-resource/delete-protect-nonempty-container.feature
protocol/writing-resource/post-target-not-found.feature

https://solidproject.org/TR/protocol#server-post-target-not-found

Test for POST to non-existing resource

---

README.md
protocol/read-write-resource/method-not-allowed.feature
web-access-control/protected-operation/read-resource-access-R.feature

You can now set the preferred HTTP version.
This means we can now test whether a server supports HTTP/2 e.g.
```
Scenario: Server supports HTTP/2
* def response = clients.alice.sendAuthorized('GET', resource.url, null, null, 'HTTP_2')
Then assert response.status == 200
And assert response.version == 'HTTP_2'
```
However, note that this is a `SHOULD` so we may need to improve the report to avoid making the test failure look like a requirement failure.

Document additional version param on send method

---

protocol/read-write-resource/method-not-allowed.feature

Following https://github.com/solid/conformance-test-harness/issues/155 I'm proposing the remove the corner case evil `DAHU` method test to. Instead, this has a `TRACE` test, which is in HTTP but not in Solid. 
Unfortunately, it is hard to have a conditional test now, and previously, I also checked the `Allow` header as that should be on every `405` but with this variability, it is hard to do, so I removed it for now.

Remove the DAHU test

---

CHANGELOG.md
protocol/writing-resource/post-target-not-found.feature

For POST to a non-existent target the test expected a 404 but if the target is not a container then surely 405 is also valid as POST may not be supported.

Fix allowed status for posting to non-existent target

---

README.md
protocol/cors/preflight-requests.feature
protocol/cors/preflight.feature
protocol/writing-resource/slash-semantics-exclude.feature

Karate added a new feature that allows headers to be fetched in a case-insensitive way. This PR documents and applies that change so that we are less vulnerable to a server using alternative versions such as `location` rather than `Location`

Make location header fetching case-insensitive

---

protocol/cors/access-control-headers.feature
protocol/cors/preflight-requests.feature
protocol/cors/preflight.feature
protocol/cors/simple-requests.feature

This PR resolves 2 issues with CORS tests:
1. `Access-Control-Allow-Credentials` was being expected when it is not required, and actually not a good thing to send so the tests no longer require it.
2. The `Vary` header was being tested for after POST requests or requests resulting in a 401 - it doesn't make sense in either situation.
Some implementations probably return some headers too often but the tests should definitely not fail when they are left off when not required.

Server not required to send Access-Control-Allow-Credentials

---

CHANGELOG.md
protocol/read-write-resource/read-method-support.feature
protocol/solid-protocol-test-manifest.ttl

This replaces https://github.com/solid-contrib/specification-tests/pull/62 as it was too difficult to merge that one but see the discussion there.

Add test to check GET,HEAD,OPTIONS are supported

---

README.md
run.sh

When I ran `./run.sh -d . css --filter=content-negotiation` I was surprised by the number of dots, at how many tests (I thought) there were in the content-negotiation category. But after reading the code of `run.sh`, I realised I had misinterpreted the dots! :) This extra console message should hopefully make that clearer.
With this change, this is what it will look like:

Make it clear that the dots mean CSS is starting

---

protocol/cors/preflight-requests.feature
protocol/cors/preflight.feature
protocol/writing-resource/slash-semantics-exclude.feature
run.sh
test-subjects.ttl

Fixes https://github.com/solid-contrib/specification-tests/issues/108
Fix run script interpolation.
Update test subject details.

Resolve location headers against base URL.

---

web-access-control/protected-operation/common.feature
web-access-control/protected-operation/read-access-agent.feature
web-access-control/protected-operation/read-access-bob.feature
web-access-control/protected-operation/read-access-public.feature
web-access-control/protected-operation/write-access-agent.feature
web-access-control/protected-operation/write-access-bob.feature
web-access-control/protected-operation/write-access-public.feature

Some Solid server implementations may propagate access policies asynchronously. In those cases, it would be useful for the test suite to make use of Karate's `retry until` mechanism.
For simple cases where the retry matches a _particular_ status code, the code for this is trivial:
And retry until responseStatus == <status>
In cases where a range of possible response status codes are possible, we needed to wrap the condition in a shared function, which is called `utils.includesExpectedStatus(actual, expected)`
For those cases, the condition becomes:
And retry until utils.includesExpectedStatus(responseStatus, <status>)

Add a retry mechanism for authorization tests

---

CHANGELOG.md
protocol/cors/acao-vary.feature
protocol/cors/accept-acah.feature
protocol/cors/access-control-headers.feature
protocol/cors/enumerate-headers.feature
protocol/cors/preflight-requests.feature
protocol/cors/preflight.feature
protocol/cors/simple-requests.feature
test-subjects.ttl

* Set the origin in CORS tests from config so that it uses the same one.
* Cast response to string when checking HEAD requests in CORS - see protocol/cors/acao-vary.feature.
Resolves #116

Make CORS test detect empty responses better
